language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
matrix:
  include:
    - env: UNDERSCORE=1.11 BACKBONE=1.4
    - env: LODASH=4.17 BACKBONE=1.4
env: MAINRUN=true
before_install:
  - npm config set ca ""
install:
  - curl -L https://rawgit.com/marionettejs/travis-ci-setup/master/ci.sh | bash
script: "npm run coverage"
after_success:
  - if [[ $MAINRUN == true ]]; then npm install -g codeclimate-test-reporter; fi
  - if [[ $MAINRUN == true ]]; then codeclimate-test-reporter < coverage/lcov.info; fi
